#!/usr/bin/env bash

#########################################

#SBATCH --time=0-00:30:00

##SBATCH --cluster=smp
##SBATCH --partition=smp

## number of nodes should be bigger than one otherwise it will complain
#SBATCH --cluster=mpi
#SBATCH --partition=ib

#########################################

#    Some Namings and email 

#########################################

#SBATCH --job-name=WeakScaling
#SBATCH --output=weak_scaling.out
#SBATCH --mail-user=cdv16@pitt.edu
#SBATCH --mail-type=END,FAIL 

########################################## 

#           Node Count 

########################################## 


#SBATCH --nodes=5

## if you specify only this the system automatically finds out the number of nodes
## on some systems they might force specification of nodes
#SBATCH --ntasks=100

# -O is used to overspecify the cores, especially beneficial for debugging
##SBATCH -O
###########################################

             # Load modules

###########################################
# module purge removes all the previously loaded modules
#module purge
module load gcc/5.4.0
module load intel/2017.1.132
module load intel-mpi/2017.1.132
module load paraview/5.3.0
module load hdf5/1.10.0
module load cmake/3.7.1
module load openmpi/2.0.2
module load zoltan/3.83.0
module load clang/5.0.0
module load doxygen/1.8.13

## you can use srun as well, or you can give the full path if you need a specific version 
# 400 points per process (x stripping)
for i in {1..10}
do
	./writedata 1 2 $((20*$i*$i)) 20
	sleep 1
	mpirun -np $(($i*$i)) main Input_Data/data_$((20*$i*$i))x20.txt $((i*i)) 1
done

